const mongoose = require('mongoose');

const ProjectSchema = new mongoose.Schema({
  title: { type: String, required: true },
   slug: { type: String,  },
  raiseFund: { type: String, },
  startDate: { type: Date ,required: true },
  endDate: { type: Date,required: true },
  smallDescription: { type: String ,required: true },
  ticker: { type: String ,},
  blockChain: [],
  category: [],
  country: { type: String,required: false },
  industry: { type: [], },
  foundedYear: { type: String, },
  whitelist: { type: String, },
  kyc: { type: String ,},
  bounty: { type: String, },
  mvp: { type: String, },
  securityAudit: { type: String, },
  tokenReview: { type: String ,},
  totalRaise: { type: String, },
  preSale: { type: String ,},
  fdv: { type: String ,},
  totalSupply: { type: String ,},
  publicSale: { type: String ,},
  initialCirculationSupply: { type: String ,},
  TelegramChannel: { type: String ,},
  twitterLink: { type: String ,},
  instagramLink: { type: String, },
  youtubeLink: { type: String ,},
  websiteLink: { type: String, },
  mediumLink: { type: String, },
  logo: { type: String, required: true },
  whitepaper: { type: String, required: true },
  roadmap: { type: String },
  projectScreeshot:{type:Array,default:[]},

  rounds:{ type: Array, default: [] },
  teams: { type: Array, default: [] },
  influencers: { type: Array, default: [] },
  partners: { type: Array, default: [] },
  sponsors: { type: Array, default: [] },
  authorName:{ type: String ,required: true },
  authorEmail:{ type: String,required: true },
  authorWhatsapp:{ type: String,required: true },
  authorTwitter:{ type: String,required: true },
  logoAltText: String,
  whitepaperAltText: String,
  roadmapAltText: String,
}, {
  timestamps: true
});

module.exports = mongoose.model('IcoListing', ProjectSchema);
